package View;

import Model.Biblioteca;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class BibliotecaView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BibliotecaView.class.getName());

    public BibliotecaView() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        initComponents();
        
        jScrollPane_biblioteca.getVerticalScrollBar().setUnitIncrement(16);
    }
    
    public void setNome(Biblioteca b) {
        jLabel_bibliotecaTitulo.setText("Biblioteca de " + b.getUsuario().getNome());
    }

    public void atualizarLista(Biblioteca b) {
        jPanel_biblioteca.removeAll();
        jPanel_biblioteca.setLayout(new BoxLayout(jPanel_biblioteca, BoxLayout.Y_AXIS));

        for (var musica : b.getBiblioteca()) {
            var linha = new JPanel();
            linha.setLayout(new BoxLayout(linha, BoxLayout.X_AXIS));
            linha.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));

            var botaoMusica = new JButton(musica.getArtista().getNome() + " - " + musica.getTitulo());
            botaoMusica.setAlignmentX(Component.LEFT_ALIGNMENT);
            botaoMusica.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
            //botaoMusica.addActionListener();

            linha.add(botaoMusica);
            linha.add(Box.createHorizontalStrut(10));
            if (b.getUsuario().equals(musica.getArtista())) {
                var botaoEditar = new JButton("Editar");
                botaoEditar.setPreferredSize(new Dimension(100, 40));
                botaoEditar.setMaximumSize(new Dimension(100, 40));
                //botaoEditar.addActionListener();
                
                linha.add(botaoEditar);
            } else {
                var placeholder = Box.createRigidArea(new Dimension(100, 40));
                
                linha.add(placeholder);
            }

            jPanel_biblioteca.add(linha);
            jPanel_biblioteca.add(Box.createVerticalStrut(5)); // espaçamento entre botões
        }

        jPanel_biblioteca.revalidate();
        jPanel_biblioteca.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_biblioteca = new javax.swing.JScrollPane();
        jPanel_biblioteca = new javax.swing.JPanel();
        jButton_adicionar = new javax.swing.JButton();
        jLabel_bibliotecaTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        javax.swing.GroupLayout jPanel_bibliotecaLayout = new javax.swing.GroupLayout(jPanel_biblioteca);
        jPanel_biblioteca.setLayout(jPanel_bibliotecaLayout);
        jPanel_bibliotecaLayout.setHorizontalGroup(
            jPanel_bibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 893, Short.MAX_VALUE)
        );
        jPanel_bibliotecaLayout.setVerticalGroup(
            jPanel_bibliotecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jScrollPane_biblioteca.setViewportView(jPanel_biblioteca);

        jButton_adicionar.setText("➕");

        jLabel_bibliotecaTitulo.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel_bibliotecaTitulo.setText("Biblioteca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_biblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel_bibliotecaTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel_bibliotecaTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_biblioteca, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BibliotecaView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_adicionar;
    private javax.swing.JLabel jLabel_bibliotecaTitulo;
    private javax.swing.JPanel jPanel_biblioteca;
    private javax.swing.JScrollPane jScrollPane_biblioteca;
    // End of variables declaration//GEN-END:variables
}
