package View;

import ChordMaker.NotaUtil;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.sound.midi.Sequence;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.event.DocumentListener;

public class EditorMusica extends JFrame {

    private List<JTextArea> jTextArea_tracks = new ArrayList<>();

    public EditorMusica() {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        initComponents();

    }

    public void setMusicaNome(String musicaNome) {
        jTextField_nomeMusica.setText(musicaNome);
    }

    public void setMusicaNomeDocumentListener(DocumentListener a) {
        jTextField_nomeMusica.getDocument().addDocumentListener(a);
    }

    public void setArtistaNome(String artistaNome) {
        jLabel_nomeArtista.setText(artistaNome);
    }

    public void setBotaoPlay(ActionListener a) {
        jButton_play.addActionListener(a);
    }

    public void setBotaoStop(ActionListener a) {
        jButton_stop.addActionListener(a);
    }

    public void setBotaoSalvar(ActionListener a) {
        jButton_salvar.addActionListener(a);
    }

    public void setAbaTrack(DocumentListener a) {
        for (var trackArea : jTextArea_tracks) {
            trackArea.getDocument().addDocumentListener(a);
        }
    }
    
    public void setBotaoRetorno(ActionListener a) {
        jButton_retornar.addActionListener(a);
    }

    public int getContagemTabs() {
        return jTabbedPane_chords.getTabCount();
    }

    private JTextArea getAreaTexto(int i) {
        var scroll = (JScrollPane) jTabbedPane_chords.getComponentAt(i);

        return (JTextArea) scroll.getViewport().getView();
    }

    public String getTextoTrack(int i) {
        var areaTexto = getAreaTexto(i);

        return areaTexto.getText();
    }

    public void setTextoTrack(int i, String texto) {
        var areaTexto = getAreaTexto(i);

        areaTexto.setText(texto);
    }

    public void setSequence(Sequence sequence) {
        // Limpar tabs antigas
        jTabbedPane_chords.removeAll();
        jTextArea_tracks.clear();

        var tracks = sequence.getTracks();

        for (int i = 0; i < tracks.length; i++) {
            var track = tracks[i];
            var textArea = new JTextArea();
            textArea.setEditable(true);

            var stringB = new StringBuilder();

            for (int j = 0; j < track.size(); j++) {
                var event = track.get(j);
                var msg = event.getMessage();
                var desc = NotaUtil.descricaoMensagem(msg);

                if (desc == null) {
                    continue;
                }

                stringB.append(String.format("Tick: %-6d | %s\n", event.getTick(), desc));
            }

            textArea.setText(stringB.toString());
            jTextArea_tracks.add(textArea);

            var scroll = new JScrollPane(textArea);
            jTabbedPane_chords.add("Track #" + i, scroll);
        }
    }

    public void setTrackCor(int i, Color cor) {
        var areaTexto = getAreaTexto(i);
        areaTexto.setBackground(cor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_nomeArtista = new javax.swing.JLabel();
        jTextField_nomeMusica = new javax.swing.JTextField();
        jTabbedPane_chords = new javax.swing.JTabbedPane();
        jButton_play = new javax.swing.JButton();
        jButton_stop = new javax.swing.JButton();
        jButton_salvar = new javax.swing.JButton();
        jButton_retornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel_nomeArtista.setText("Artista");

        jTextField_nomeMusica.setText("Titulo");

        jButton_play.setText("▶");

        jButton_stop.setText("⏹");

        jButton_salvar.setText("💾");

        jButton_retornar.setText("⬅");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField_nomeMusica)
                    .addComponent(jLabel_nomeArtista, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_retornar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(415, 415, 415)
                        .addComponent(jButton_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_play, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane_chords, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_retornar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField_nomeMusica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_nomeArtista))
                    .addComponent(jTabbedPane_chords, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_play, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_play;
    private javax.swing.JButton jButton_retornar;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JButton jButton_stop;
    private javax.swing.JLabel jLabel_nomeArtista;
    private javax.swing.JTabbedPane jTabbedPane_chords;
    private javax.swing.JTextField jTextField_nomeMusica;
    // End of variables declaration//GEN-END:variables
}
